language: ruby
rvm:
  - 2.1
script:
  - bundle exec jekyll build
  - bundle exec htmlproofer ./_site --allow-hash-href --alt-ignore /assets/imgs/gallery/* --empty-alt-ignore --external_only --url-ignore https://www.facebook.com/matthew.sommer,https://www.linkedin.com/in/matthewsommer,https://angel.co/matt-sommer
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer