# Jekyll Global Configuration Settings
# 'bundle exec jekyll serve' cmd to build and serve site


title: MattSommer.io
email: matthew.sommer@gmail.com
description: >
  Matt Sommer is a human, being; this is a website about his being. 
  He enjoys travel, engineering (mechanical, electrical, computer), 
  visual arts (film, photography, drawing,+), outdoor activites such as hiking and skiing.
baseurl: ""
url: "http://mattsommer.io"
twitter_username: yerself
github_username:  matthewsommer
repository: matthewsommer/matthewsommer.github.io
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-assets

sass:
  style: compressed
  
defaults:
  - scope:
      path: "assets/imgs/gallery"
    values:
      gallery: true

include: 
  - _pages

exclude:
  - Gemfile
  - Gemfile.lock
  - CNAME
  - vendor
